### ISSUE TITLE
Problémes avec les workflows de construction des images

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-py-platform#14]
La gestion des images *-dev ne semble pas correct dans le dockerfile:
![image](https://user-images.githubusercontent.com/1451383/203907432-836cad02-4c31-4880-880e-f74f61ebe62b.png)

**Comment by XdoctorwhoZ** [comment]
Est-ce que ces warning sont normaux ? n'y a t-il pas une meilleure solution ?
![image](https://user-images.githubusercontent.com/1451383/203908432-b10e097e-0552-4750-8790-46c633b752cc.png)

**Comment by XdoctorwhoZ** [comment]
Pourquoi avoir utilisé docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c ?
et non pas docker/login-action@v2 ?

les problèmes semblent venir de la.

**Comment by XdoctorwhoZ** [comment]
Pour t'aider sur le dockerfile j'ai fait le script "source docker.build-image.sh" 
tu peux build ton dockerfile en local

**Comment by XdoctorwhoZ** [comment]
@JJJul1en 
Une fois l'image build tu peux lancer

```bash
docker run local/panduza-py-platform:latest
```

et tu devrais avoir:

```
DEBUG     |+++       > ==========================================
DEBUG     |+++       > =         PANDUZA PY PLATFORM            =
DEBUG     |+++       > ==========================================
DEBUG     |+++       > Start plugin discovery
DEBUG     |+++       > Discovered plugins: {}
INFO      |+++       > Register driver: 'platform_py'
INFO      |+++       > Register driver: 'io_fake'
INFO      |+++       > Register driver: 'psu_fake'
INFO      |+++       > Register driver: 'file_fake'
INFO      |+++       > Register driver: 'reset_fake'
INFO      |+++       > Register driver: 'register_fake'

ICI IL FAUT DES DRIVERS EN PLUS (CEUX QUI SONT INSTALLE AVEC LES PACKAGES EN PLUS

CRITICAL  |+++       > Platform configuration file (tree.json) has not been found at location (/etc/panduza/tree.json) !!==>> STOP PLATFORM
WARNING   |+++       > Platform stopped !
```

**Comment by JJJul1en** [comment]
> La gestion des images *-dev ne semble pas correct dans le dockerfile: ![image](https://user-images.githubusercontent.com/1451383/203907432-836cad02-4c31-4880-880e-f74f61ebe62b.png)

Non elle n'est pas correcte.
Je voulais voir avec toi s'il y avait une variable d'environnement contenant le nom de l'image qui est build afin de faire du pattern matching dessus.

**Comment by JJJul1en** [comment]
> Pourquoi avoir utilisé [docker/login-action@28218f9](https://github.com/docker/login-action/commit/28218f9b04b4f3f62068d7b6ce6ca5b26e35336c) ? et non pas docker/login-action@v2 ?
> 
> les problèmes semblent venir de la.

J'ai utilisé un fichier généré par défaut par GitHub.
Je vais changer l'action.

**Comment by XdoctorwhoZ** [comment]
> > La gestion des images *-dev ne semble pas correct dans le dockerfile: ![image](https://user-images.githubusercontent.com/1451383/203907432-836cad02-4c31-4880-880e-f74f61ebe62b.png)
> 
> Non elle n'est pas correcte. Je voulais voir avec toi s'il y avait une variable d'environnement contenant le nom de l'image qui est build afin de faire du pattern matching dessus.

ne pas faire de pull request si tu sais qu'il y a un probléme... ou au moins l'indiquer dans la pull request.
