### ISSUE TITLE
Merge des workflows qui ont les mémes conditions

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-py-platform#15]
Je pense que 4 workflows c'est trop pour la gestion des images.
Je souhaiterai:

- 1 workflow pour les latest (avec 2 jobs, l'image prod et celle -dev)
- 1 workflow pour les versions (avec 2 jobs, l'image prod et celle -dev)

merci @JJJul1en

**Comment by JJJul1en** [comment]
C'est dans extract que je spécifie le nom de l'image à build.
Je ne peux pas mettre deux extract dans mon workflow si ?

**Comment by XdoctorwhoZ** [comment]
Dans le Dockerfile, recupére l'information prod/dev depuis une variable d'environnement par exemple PZA_PY_PLATFORM_MODE="prod" ou "dev" (si rien c'est prod par default)
Puis tu injectes ça dans ton job avec env:
