### ISSUE TITLE
Docker prod images produced from actions does not include plugins

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-py-platform#23]
@JJJul1en tu as oublié d'ajouter ton system avec PZA_PY_PLATFORM_MODE  dans les workflows

Pour tester 

```bash
docker run \
    --network host \
    -v $PWD:/etc/panduza \
    -v /run/udev:/run/udev:ro \
    ghcr.io/panduza/panduza-py-platform:latest
```

tu dois avoir les plugins en plus par rapport à la -dev

**Comment by JJJul1en** [comment]
Commande :
➜  ~ sudo docker run \
    --network host \
    -v $PWD:/etc/panduza \
    -v /run/udev:/run/udev:ro \
    ghcr.io/jjjul1en/panduza-py-platform:latest

Résultat :

![image](https://user-images.githubusercontent.com/50075377/205015065-b93e5c31-04a2-45ab-bef7-2cb70cf9a154.png)

**Comment by JJJul1en** [comment]
Avec l'image dev :

![image](https://user-images.githubusercontent.com/50075377/205015574-43b1334d-586e-4c5d-9454-9e6ce1bf33a6.png)

**Comment by JJJul1en** [comment]
Je pense qu'on peut fermer l'issue
